// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID         pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Tag        int32
	TagText    string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	EventCalID pgtype.Text
	Names      []string
	PostedAts  []pgtype.Timestamptz
	PostUrls   []string
	PostIds    []pgtype.UUID
	SiteID     pgtype.UUID
}

type Post struct {
	ID         pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Name       string
	Tag        int32
	TagText    string
	PostedAt   pgtype.Timestamptz
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	Body       string
	PostUrl    string
	SiteID     pgtype.UUID
	Registered bool
}

type Site struct {
	ID            pgtype.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	LastFetchedAt pgtype.Timestamp
	Name          string
	Url           string
}
