// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Tag       int32
	TagText   string
	StartsAt  sql.NullTime
	EndsAt    sql.NullTime
	Names     []string
	PostedAts []time.Time
	PostUrls  []string
	PostIds   []uuid.UUID
	SiteID    uuid.UUID
}

type Post struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Tag       int32
	TagText   string
	PostedAt  time.Time
	StartsAt  sql.NullTime
	EndsAt    sql.NullTime
	Body      string
	PostUrl   string
	SiteID    uuid.UUID
}

type Site struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastFetchedAt sql.NullTime
	Name          string
	Url           string
}
